POST {{host}}/api/1/color_map/process/3d/ HTTP/1.1
Content-Type: application/json

{
  "activation": "26e20092-0d75-47f7-8ba4-7ce4f42d904e",
  "color_map": "00dde256-256e-4ebf-b9e9-76222f009c56",
  "normalization": "local"
}
