### Global
POST {{host}}/api/1/network_input/process/ HTTP/1.1
Content-Type: application/json

{
  "architecture": "a3e71a72-dc30-417a-b09f-b29235b580c7",
  "layer_index": 4,
  "network_input": "fd0171fa-17c3-4fe1-a4e6-85847995cf1c",
  "normalization": "local"
}

### Local
POST {{host}}/api/1/network_input/process/ HTTP/1.1
Content-Type: application/json

{
  "architecture": "a3e71a72-dc30-417a-b09f-b29235b580c7",
  "layer_index": 4,
  "network_input": "fd0171fa-17c3-4fe1-a4e6-85847995cf1c",
  "normalization": "global"
}
